# FinSim
#
# Copyright 2019 Carnegie Mellon University. All Rights Reserved.
#
# NO WARRANTY. THIS CARNEGIE MELLON UNIVERSITY AND SOFTWARE ENGINEERING INSTITUTE MATERIAL IS FURNISHED ON AN "AS-IS" BASIS. CARNEGIE MELLON UNIVERSITY MAKES NO WARRANTIES OF ANY KIND, EITHER EXPRESSED OR IMPLIED, AS TO ANY MATTER INCLUDING, BUT NOT LIMITED TO, WARRANTY OF FITNESS FOR PURPOSE OR MERCHANTABILITY, EXCLUSIVITY, OR RESULTS OBTAINED FROM USE OF THE MATERIAL. CARNEGIE MELLON UNIVERSITY DOES NOT MAKE ANY WARRANTY OF ANY KIND WITH RESPECT TO FREEDOM FROM PATENT, TRADEMARK, OR COPYRIGHT INFRINGEMENT.
#
# Released under a MIT (SEI)-style license, please see license.txt or contact permission@sei.cmu.edu for full terms.
#
# [DISTRIBUTION STATEMENT A] This material has been approved for public release and unlimited distribution.  Please see Copyright notice for non-US Government use and distribution.
#
# This Software includes and/or makes use of the following Third-Party Software subject to its own license:
#
# 1. Django (https://www.djangoproject.com/foundation/faq/) Copyright 2005-2018 Django Software Foundation.
# 2. bootstrap (https://getbootstrap.com/docs/4.0/about/license/) Copyright 2018 Twitter.
# 3. glyphicons (https://www.glyphicons.com/license/) Copyright 2010-2018 GLYPHICONS.
# 4. jquery (https://jquery.org/license/) Copyright 2018 jquery foundation.
# 5. jquery tablesorter (https://mottie.github.io/tablesorter/docs/) Copyright 2007-2018 Christian Bach, Rob Garrison and Contributing Authors (see AUTHORS file).
# 6. jquery validate (https://jqueryvalidation.org/) Copyright 2006-2018 J�rn Zaefferer,  Markus Staab, Brahim Arkni, and contributors .
# 7. jquery validate unobtrusive (https://github.com/aspnet/jquery-validation-unobtrusive/blob/master/LICENSE.txt) Copyright 2014-2018 .NET Foundation.
# 8. modernizr (https://github.com/Modernizr/Modernizr/blob/master/LICENSE) Copyright 2009-2018 https://github.com/Modernizr/Modernizr/graphs/contributors.
# 9. respond.js (https://github.com/scottjehl/Respond) Copyright 2011 Scott Jehl.
# 10. roboto fonts (https://fonts.google.com/specimen/Roboto) Copyright 2015-2018 Google, Inc..
# 11. xregexp (http://xregexp.com/) Copyright 2007-2012 Steven Levithan.
#
# DM19-0396
#

# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-28 13:54
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Address', models.CharField(blank=True, default=b'', max_length=80)),
                ('City', models.CharField(blank=True, default=b'', max_length=30)),
                ('State', models.CharField(blank=True, default=b'', max_length=30)),
                ('ZipCode', models.CharField(blank=True, default=b'', max_length=30)),
                ('Balance', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15)),
                ('Approved', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(999999999)])),
                ('Denied', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(999999999)])),
                ('Transactions', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(999999999)])),
                ('AccountNumber', models.CharField(blank=True, default=b'', max_length=30, unique=True)),
                ('Company', models.CharField(blank=True, default=b'', max_length=30)),
                ('PointOfContact', models.TextField(blank=True, max_length=255)),
                ('Identifier', models.TextField(blank=True, default=b'[]', max_length=255)),
                ('KeyLocation', models.FilePathField(blank=True, default=b'DNF')),
                ('Domain', models.URLField(blank=True, default=b'DNF')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('Balance', 'AccountNumber', 'Company'),
            },
        ),
        migrations.CreateModel(
            name='CommercialTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('FirstName', models.CharField(blank=True, default=b'', max_length=30)),
                ('LastName', models.CharField(blank=True, default=b'', max_length=30)),
                ('MiddleIntial', models.CharField(blank=True, default=b'', max_length=2)),
                ('Address', models.CharField(blank=True, default=b'', max_length=80)),
                ('City', models.CharField(blank=True, default=b'', max_length=20)),
                ('State', models.CharField(blank=True, default=b'', max_length=10)),
                ('ZipCode', models.CharField(blank=True, default=b'', max_length=10)),
                ('Invoice', models.CharField(blank=True, default=b'', max_length=30)),
                ('Confirmations', models.CharField(blank=True, default=b'', max_length=30)),
                ('AuthType', models.CharField(blank=True, default=b'', max_length=20)),
                ('PrimaryAmount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15)),
                ('CardNumber', models.CharField(blank=True, default=b'', max_length=16)),
                ('ExpDate', models.CharField(blank=True, default=b'', max_length=5)),
                ('CVV2', models.CharField(blank=True, default=b'', max_length=4)),
                ('ResponseCode', models.CharField(blank=True, default=b'', max_length=30)),
                ('AVS', models.CharField(blank=True, default=b'', max_length=5)),
            ],
            options={
                'ordering': ('Invoice',),
            },
        ),
        migrations.CreateModel(
            name='UserAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Address', models.CharField(blank=True, default=b'', max_length=80)),
                ('City', models.CharField(blank=True, default=b'', max_length=30)),
                ('State', models.CharField(blank=True, default=b'', max_length=30)),
                ('ZipCode', models.CharField(blank=True, default=b'', max_length=30)),
                ('Balance', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15)),
                ('Approved', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(999999999)])),
                ('Denied', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(999999999)])),
                ('Transactions', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(999999999)])),
                ('AccountNumber', models.CharField(blank=True, default=b'', max_length=30, unique=True)),
                ('MiddleInitialntial', models.CharField(blank=True, default=b'', max_length=30)),
                ('SSN', models.CharField(blank=True, default=b'', max_length=30, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('Balance', 'AccountNumber'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('FirstName', models.CharField(blank=True, default=b'', max_length=30)),
                ('LastName', models.CharField(blank=True, default=b'', max_length=30)),
                ('MiddleIntial', models.CharField(blank=True, default=b'', max_length=2)),
                ('Address', models.CharField(blank=True, default=b'', max_length=80)),
                ('City', models.CharField(blank=True, default=b'', max_length=20)),
                ('State', models.CharField(blank=True, default=b'', max_length=10)),
                ('ZipCode', models.CharField(blank=True, default=b'', max_length=10)),
                ('Invoice', models.CharField(blank=True, default=b'', max_length=30)),
                ('Confirmations', models.CharField(blank=True, default=b'', max_length=30)),
                ('AuthType', models.CharField(blank=True, default=b'', max_length=20)),
                ('PrimaryAmount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15)),
                ('AccountNumber', models.CharField(blank=True, default=b'', max_length=30)),
            ],
            options={
                'ordering': ('AccountNumber',),
            },
        ),
    ]
